package com.yed.bean;

public class Family {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.id
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.name
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family.relation
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    private String relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.id
     *
     * @return the value of family.id
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.id
     *
     * @param id the value for family.id
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.name
     *
     * @return the value of family.name
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.name
     *
     * @param name the value for family.name
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family.relation
     *
     * @return the value of family.relation
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family.relation
     *
     * @param relation the value for family.relation
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }
}