package com.yed.dao;

import com.yed.bean.Family;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    Family selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family
     *
     * @mbggenerated Mon Jun 19 09:39:04 CST 2017
     */
    int updateByPrimaryKey(Family record);
}